---
# powersave Intel.yml
# Only enable powersave options on server systems with Intel CPUs
# As we are here, presence of Intel CPU is assumed.
# If this is a "dev_workstation", we set for max performance

- name: Ensure cpufrequtils is installed
  ansible.builtin.apt:
    name: cpufrequtils
    state: present
  when: ansible_distribution_release == "bookworm"

- name: Set desired governor based on group
  ansible.builtin.set_fact:
    desired_governor: "{{ 'performance' if 'dev_workstation' in group_names else 'powersave' }}"

- name: Include tasks to deal with powertop
  ansible.builtin.include_tasks: powertop.yml

- name: Set powersave governor to desired value
  ansible.builtin.template:
    src: etc/default/cpufrequtils.j2
    dest: /etc/default/cpufrequtils
    owner: root
    group: root
    mode: "0644"
  when: ansible_distribution_release == "bookworm"
