---
# powersave Raspberry.yml
- name: For raspberry, make sure there is no cpufrequtils
  ansible.builtin.apt:
    name: cpufrequtils
    state: absent
    purge: true
    autoremove: true

- name: Set desired governor
  ansible.builtin.set_fact:
    desired_governor: 'ondemand'

- name: Process effects for powertop
  ansible.builtin.include_tasks:
    file: powertop.yml
